---
- name: Add nodejs PPA key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add nodejs repo
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: nodejs
    update_cache: yes
  with_items:
    - "deb https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_10.x {{ ansible_distribution_release }} main"

- name: Install nodejs
  become: yes
  environment:
    PATH: /bin:/sbin:/usr/bin:/usr/sbin
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 86400
  with_items: "{{ nodejs_packages }}"
