---
- name: Install redis-server
  become: yes
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  apt:
    name: "redis-server=3:3.2*"
    state: present
    cache_valid_time: 86400
