---
- name: Install some common stuff
  become: yes
  environment:
    PATH: /bin:/sbin:/usr/bin:/usr/sbin
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 86400
  with_items: "{{ common_packages }}"
