---
- name: Need to enable the dwc2 driver in boot config
  lineinfile:
    path: /boot/config.txt
    regexp: '^dtoverlay='
    line: 'dtoverlay=dwc2'
  register: updatedBootConfig

- name: Need to add dwc2 and config to OS modules
  lineinfile:
    path: /etc/modules
    regexp: '{{ item.reg }}'
    line: '{{ item.line }}'
  register: updatedModules
  with_items:
    - {reg: '^dwc2$', line:'dwc2'}
#    - {reg: '^g_ether$', line:'g_ether'}
